modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="quantumsystem"
displayName="Quantum System"
version="${file.jarVersion}"
credits="Caseofgames, for the development of this mod. Darkhax, for a class I 'borrowed.'"
authors="Caseofgames"

description='''
You ever wanted to play with quantum mechanics? Now you can!
'''